version: "3.9"

services:
  gateway:
    image: gateway-service:latest
    #    image: inreven/consolere-utils:0.5
    networks:
      - asd
    ports:
      - "8080:8080"

  grpc-auth-service:
    container_name: grpc-auth-service
    networks:
      - asd
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - migrate

  db:
    restart: always
    image: postgres:latest
    networks:
      - asd
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: pg_isready --username ${DB_USER} --dbname ${DB_NAME}
      interval: 1s
      retries: 3
      timeout: 5s

  migrate:
    image: migrate/migrate:latest
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    networks:
      - asd
    command: '-path /migrations/ -database "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=${DB_SSL_MODE}" up'

networks:
  asd:
    driver: bridge